# Generated by Django 3.1.7 on 2021-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('localite', models.CharField(max_length=100)),
                ('nombre_de_personnes', models.IntegerField()),
                ('nbre_etoile_hotel', models.IntegerField()),
                ('forme_de_tourisme', models.CharField(max_length=100)),
                ('emails', models.EmailField(max_length=254)),
                ('nombre_de_lieux_a_visiter', models.IntegerField()),
                ('types_de_transport', models.CharField(max_length=200)),
                ('commentaires', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
